/**
 * sdd arch — generate architecture views from specs
 * Invokes Claude Code to read all specs and generate Mermaid + HTML dashboard.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';
import ora from 'ora';
import { readAllSpecs, readSteering, readModuleSpecs } from '../core/spec-reader.js';
import { generateArchitecture, parseArchSections, Mode } from '../core/generator.js';
import { createProgress } from '../core/progress.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_PATH = path.join(__dirname, '../../templates/arch-dashboard.html');

export async function archCmd({ level, flow, output, promptOnly, cwd = process.cwd() }) {
  console.log(`\n${chalk.bold('sdd arch')} — ${chalk.cyan('Architecture View')}`);

  const specs = readAllSpecs(cwd);
  const steering = readSteering(cwd);
  const moduleSpecs = readModuleSpecs(cwd);

  const moduleCount = Object.keys(moduleSpecs).length;
  const specCount = specs.length;
  const steeringCount = Object.keys(steering).length;

  if (!specCount && !steeringCount && !moduleCount) {
    console.log(chalk.yellow('\n  No specs found. Run `sdd spec document` or `sdd spec create` first.'));
    console.log(chalk.dim('  Expected: specs/_modules/, specs/features/*/, or .claude/steering/\n'));
    return;
  }

  console.log(chalk.dim(`  Reading ${moduleCount} module spec(s), ${specCount} feature spec(s), ${steeringCount} steering file(s)\n`));

  const spinner = ora('Generating architecture via Claude Code...').start();

  const onProgress = createProgress(spinner);

  try {
    const result = await generateArchitecture({ promptOnly, cwd, moduleSpecs, steering, featureSpecs: specs, onProgress });

    if (result.mode === Mode.PROMPT) {
      spinner.info('Claude Code not found — prompt saved');
      const outDir = path.join(cwd, 'specs', '_arch');
      fs.mkdirSync(outDir, { recursive: true });
      const promptPath = path.join(outDir, 'arch_prompt.md');
      fs.writeFileSync(promptPath, result.prompt, 'utf-8');
      console.log(chalk.dim(`  ${path.relative(cwd, promptPath)}`));
      console.log(chalk.dim(`\n  Paste the prompt into Claude Code to generate architecture views.`));
      console.log('');
      return;
    }

    spinner.succeed('Architecture generated by Claude Code');

    // Claude Code wrote architecture.md — parse it and build dashboard
    const outDir = path.join(cwd, 'specs', '_arch');
    const mdPath = path.join(outDir, 'architecture.md');

    if (fs.existsSync(mdPath)) {
      const archContent = fs.readFileSync(mdPath, 'utf-8');
      const sections = parseArchSections(archContent);

      // Build HTML dashboard from the Mermaid content
      const html = buildDashboard(sections, specs, steering);
      const htmlPath = path.join(outDir, 'dashboard.html');
      fs.writeFileSync(htmlPath, html, 'utf-8');

      // Save summary as JSON
      if (sections.summary) {
        const jsonPath = path.join(outDir, 'architecture.json');
        fs.writeFileSync(jsonPath, JSON.stringify(sections.summary, null, 2), 'utf-8');
      }

      const summary = sections.summary;
      if (summary) {
        console.log(chalk.bold('  System: ') + (summary.system_name || path.basename(cwd)));
        if (summary.description) console.log(chalk.bold('  About:  ') + chalk.dim(summary.description));
        if (summary.components?.length) console.log(chalk.bold('  Components: ') + summary.components.length);
      }

      console.log('');
      console.log(chalk.dim('  Files:'));
      console.log(`  ${chalk.green('>')} specs/_arch/architecture.md`);
      console.log(`  ${chalk.green('>')} specs/_arch/architecture.json`);
      console.log(`  ${chalk.green('>')} specs/_arch/dashboard.html`);
      console.log('');
      console.log(chalk.dim(`  Open dashboard: ${chalk.cyan('open specs/_arch/dashboard.html')}`));
    } else {
      console.log(chalk.dim('\n  Check specs/_arch/ for generated files.'));
    }
    console.log('');

  } catch (err) {
    onProgress.stop();
    spinner.fail('Failed to generate architecture');
    console.error(chalk.red(`\n  ${err.message}\n`));
  }
}

// ─── Build HTML dashboard ─────────────────────────────────────────────────

function buildDashboard(sections, specs, steering) {
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf-8');
  const s = sections.summary || {};

  // Use feature specs from disk if available, otherwise use SUMMARY features from architecture analysis
  const features = specs.length > 0
    ? specs.map(spec => ({
        name: spec.name,
        done: spec.tasks.filter(t => t.done).length,
        total: spec.tasks.length,
        status: spec.tasks.length === 0 ? 'planned'
          : spec.tasks.every(t => t.done) ? 'complete' : 'in-progress',
      }))
    : (s.features || []).map(f => ({
        name: f.name,
        done: f.tasks_done || 0,
        total: f.tasks_total || 0,
        status: f.status || 'planned',
      }));

  const totalTasks = features.reduce((n, f) => n + f.total, 0);
  const tasksDone  = features.reduce((n, f) => n + f.done, 0);
  const complete   = features.filter(f => f.total > 0 && f.done === f.total).length;

  const featureRows = features.map(f => {
    const pct = f.total ? Math.round((f.done / f.total) * 100) : 0;
    const st = f.total === 0 ? 'planned' : pct === 100 ? 'complete' : 'progress';
    const color = { complete: 'var(--green)', progress: 'var(--orange)', planned: 'var(--muted)' }[st];
    return `<li class="feature-item">
      <div class="feature-name">${f.name}</div>
      <div class="feature-meta">${f.done}/${f.total} tasks</div>
      <div class="progress-bar"><div class="progress-fill" style="width:${pct}%;background:${color}"></div></div>
      <span class="badge badge-${st}">${st}</span>
    </li>`;
  }).join('\n');

  const compRows = (s.components || []).map(c =>
    `<tr><td>${c.name}</td><td class="type-${c.type}">${c.type}</td><td>${c.description || ''}</td></tr>`
  ).join('\n');

  const techTags = (s.tech_stack || []).map(t => `<span class="tag">${t}</span>`).join('');
  const decisions = (s.key_decisions || []).map(d => `<div class="decision">${d}</div>`).join('');

  const flows = sections.flows || {};
  const flowNav = Object.keys(flows).map(name => {
    const id = slugify(name);
    return `<button class="nav-link" onclick="showView('flow-${id}', this)">
      <span class="dot" style="background:var(--accent)"></span> ${name}
    </button>`;
  }).join('\n');

  const flowViews = Object.entries(flows).map(([name, diagram]) => {
    const id = slugify(name);
    return `<div id="view-flow-${id}" class="view">
      <div class="page-header"><h1>Flow: ${name}</h1></div>
      <div class="card">
        <div class="diagram-container">
          <pre class="mermaid">${diagram}</pre>
        </div>
      </div>
    </div>`;
  }).join('\n');

  return template
    .replace(/{{SYSTEM_NAME}}/g, s.system_name || path.basename(process.cwd()))
    .replace(/{{DESCRIPTION}}/g, s.description || 'Generated from SDD specs')
    .replace(/{{TOTAL_FEATURES}}/g, features.length)
    .replace(/{{COMPLETE_FEATURES}}/g, complete)
    .replace(/{{TOTAL_TASKS_DONE}}/g, tasksDone)
    .replace(/{{TOTAL_TASKS}}/g, totalTasks)
    .replace(/{{OVERVIEW_DIAGRAM}}/g, sections.overview || 'graph TD\n  A[No data]')
    .replace(/{{SERVICES_DIAGRAM}}/g, sections.services || 'graph LR\n  A[No data]')
    .replace(/{{MODULES_DIAGRAM}}/g, sections.modules || 'graph TD\n  A[No data]')
    .replace(/{{TECH_TAGS}}/g, techTags || '<span class="tag">Not specified</span>')
    .replace(/{{DECISIONS}}/g, decisions || '<div class="decision">No decisions recorded</div>')
    .replace(/{{COMPONENTS_ROWS}}/g, compRows || '<tr><td colspan="3" style="color:var(--muted)">No components found</td></tr>')
    .replace(/{{FEATURE_ROWS}}/g, featureRows || '<li class="feature-item"><div class="feature-name">No features</div></li>')
    .replace(/{{FLOW_NAV}}/g, flowNav)
    .replace(/{{FLOW_VIEWS}}/g, flowViews);
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
