/**
 * sdd arch — generate architecture views from specs
 * Reads all specs + steering, calls Claude, outputs Mermaid + HTML.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';
import ora from 'ora';
import { readAllSpecs, readSteering } from '../core/spec-reader.js';
import { generateArchitecture, parseArchSections, detectMode, Mode } from '../core/generator.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_PATH = path.join(__dirname, '../../templates/arch-dashboard.html');

export async function archCmd({ level, flow, output, promptOnly, cwd = process.cwd() }) {
  console.log(`\n${chalk.bold('🏗  sdd arch')} — ${chalk.cyan('Architecture View')}`);

  const specs = readAllSpecs(cwd);
  const steering = readSteering(cwd);

  if (!specs.length && !Object.keys(steering).length) {
    console.log(chalk.yellow('\n  No specs found. Run `sdd spec create` first.'));
    console.log(chalk.dim('  Expected: specs/features/*/ or .claude/steering/\n'));
    return;
  }

  const specCount = specs.length;
  const steeringCount = Object.keys(steering).length;
  console.log(chalk.dim(`  Reading ${specCount} feature spec(s), ${steeringCount} steering file(s)\n`));

  const spinner = ora('Generating architecture...').start();

  try {
    const result = await generateArchitecture({ specs, steering, promptOnly });
    spinner.stop();

    if (result.mode === Mode.PROMPT) {
      // Prompt-only mode
      const outDir = path.join(cwd, 'specs', '_arch');
      fs.mkdirSync(outDir, { recursive: true });
      const promptPath = path.join(outDir, 'arch_prompt.md');
      fs.writeFileSync(promptPath, result.raw, 'utf-8');
      console.log(chalk.yellow('\n  Prompt saved (no API key detected):'));
      console.log(chalk.dim(`  ${path.relative(cwd, promptPath)}\n`));
      return;
    }

    // Parse Claude's response
    const sections = parseArchSections(result.raw);

    // Write Mermaid architecture.md
    const archMd = buildArchMarkdown(sections, specs);
    const outDir = path.join(cwd, 'specs', '_arch');
    fs.mkdirSync(outDir, { recursive: true });

    const mdPath = path.join(outDir, 'architecture.md');
    fs.writeFileSync(mdPath, archMd, 'utf-8');

    // Write HTML dashboard
    const html = buildDashboard(sections, specs, steering);
    const htmlPath = path.join(outDir, 'dashboard.html');
    fs.writeFileSync(htmlPath, html, 'utf-8');

    // Summary
    const summary = sections.summary;
    console.log(chalk.green.bold(`  ✓ Architecture generated\n`));

    if (summary) {
      console.log(chalk.bold('  System: ') + (summary.system_name || path.basename(cwd)));
      console.log(chalk.bold('  About:  ') + chalk.dim(summary.description || ''));
      if (summary.components?.length) {
        console.log(chalk.bold('  Components: ') + summary.components.length);
      }
    }

    console.log('');
    console.log(chalk.dim('  Files written:'));
    console.log(`  ${chalk.green('✓')} ${path.relative(cwd, mdPath)}`);
    console.log(`  ${chalk.green('✓')} ${path.relative(cwd, htmlPath)}`);
    console.log('');
    console.log(chalk.dim(`  Open dashboard: ${chalk.cyan('open ' + path.relative(cwd, htmlPath))}`));
    console.log('');

  } catch (err) {
    spinner.fail('Failed to generate architecture');
    console.error(chalk.red(`\n  ${err.message}\n`));
    if (err.message.includes('API')) {
      console.log(chalk.dim('  Set ANTHROPIC_API_KEY or use --prompt-only\n'));
    }
  }
}

// ─── Build architecture.md ─────────────────────────────────────────────────

function buildArchMarkdown(sections, specs) {
  const lines = [
    '# Architecture',
    '',
    `> Generated by sdd-kit from ${specs.length} feature specs`,
    '',
    '## System Overview',
    '',
  ];

  if (sections.overview) {
    lines.push('```mermaid', sections.overview, '```', '');
  }

  if (sections.services) {
    lines.push('## Services', '', '```mermaid', sections.services, '```', '');
  }

  if (sections.modules) {
    lines.push('## Modules', '', '```mermaid', sections.modules, '```', '');
  }

  if (Object.keys(sections.flows).length) {
    lines.push('## Feature Flows', '');
    for (const [name, diagram] of Object.entries(sections.flows)) {
      lines.push(`### ${name}`, '', '```mermaid', diagram, '```', '');
    }
  }

  if (sections.summary) {
    const s = sections.summary;
    lines.push('## Summary', '');
    if (s.description) lines.push(s.description, '');
    if (s.tech_stack?.length) {
      lines.push('**Tech stack:** ' + s.tech_stack.join(', '), '');
    }
    if (s.key_decisions?.length) {
      lines.push('**Key decisions:**');
      for (const d of s.key_decisions) lines.push(`- ${d}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ─── Build HTML dashboard ─────────────────────────────────────────────────

function buildDashboard(sections, specs, steering) {
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf-8');
  const s = sections.summary || {};

  // Stats
  const totalTasks = specs.reduce((n, s) => n + s.tasks.length, 0);
  const tasksDone  = specs.reduce((n, s) => n + s.tasks.filter(t => t.done).length, 0);
  const complete   = specs.filter(s => s.tasks.length > 0 && s.tasks.every(t => t.done)).length;

  // Feature rows
  const featureRows = specs.map(spec => {
    const done = spec.tasks.filter(t => t.done).length;
    const total = spec.tasks.length;
    const pct = total ? Math.round((done / total) * 100) : 0;
    const status = total === 0 ? 'planned' : pct === 100 ? 'complete' : 'progress';
    const color = { complete: '#3fb950', progress: '#f0883e', planned: '#7d8590' }[status];
    return `<li class="feature-item">
      <div class="feature-name">${spec.name}</div>
      <div class="feature-meta">${done}/${total} tasks</div>
      <div class="progress-bar"><div class="progress-fill" style="width:${pct}%;background:${color}"></div></div>
      <span class="badge badge-${status}">${status}</span>
    </li>`;
  }).join('\n');

  // Components table
  const compRows = (s.components || []).map(c =>
    `<tr><td>${c.name}</td><td class="type-${c.type}">${c.type}</td><td>${c.description || ''}</td></tr>`
  ).join('\n');

  // Tech tags
  const techTags = (s.tech_stack || []).map(t => `<span class="tag">${t}</span>`).join('');

  // Key decisions
  const decisions = (s.key_decisions || []).map(d => `<div class="decision">${d}</div>`).join('');

  // Flow nav + views
  const flows = sections.flows || {};
  const flowNav = Object.keys(flows).map(name => {
    const id = slugify(name);
    return `<button class="nav-link" onclick="showView('flow-${id}')">
      <span class="dot" style="background:#58a6ff"></span> ${name}
    </button>`;
  }).join('\n');

  const flowViews = Object.entries(flows).map(([name, diagram]) => {
    const id = slugify(name);
    return `<div id="view-flow-${id}" class="view">
      <div class="page-header"><h1>Flow: ${name}</h1></div>
      <div class="card">
        <div class="diagram-container">
          <pre class="mermaid">${diagram}</pre>
        </div>
      </div>
    </div>`;
  }).join('\n');

  return template
    .replace(/{{SYSTEM_NAME}}/g, s.system_name || path.basename(process.cwd()))
    .replace(/{{DESCRIPTION}}/g, s.description || 'Generated from SDD specs')
    .replace(/{{TOTAL_FEATURES}}/g, specs.length)
    .replace(/{{COMPLETE_FEATURES}}/g, complete)
    .replace(/{{TOTAL_TASKS_DONE}}/g, tasksDone)
    .replace(/{{TOTAL_TASKS}}/g, totalTasks)
    .replace(/{{OVERVIEW_DIAGRAM}}/g, sections.overview || 'graph TD\n  A[No data]')
    .replace(/{{SERVICES_DIAGRAM}}/g, sections.services || 'graph LR\n  A[No data]')
    .replace(/{{MODULES_DIAGRAM}}/g, sections.modules || 'graph TD\n  A[No data]')
    .replace(/{{TECH_TAGS}}/g, techTags || '<span class="tag">Not specified</span>')
    .replace(/{{DECISIONS}}/g, decisions || '<div class="decision">No decisions recorded</div>')
    .replace(/{{COMPONENTS_ROWS}}/g, compRows || '<tr><td colspan="3" style="color:var(--muted)">No components found</td></tr>')
    .replace(/{{FEATURE_ROWS}}/g, featureRows || '<li class="feature-item"><div class="feature-name">No features</div></li>')
    .replace(/{{FLOW_NAV}}/g, flowNav)
    .replace(/{{FLOW_VIEWS}}/g, flowViews);
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
