/**
 * sdd spec create — generate spec files from a feature description
 */

import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { readSteering, readModuleSpecs } from '../../core/spec-reader.js';
import { generateCreateSpec, Mode } from '../../core/generator.js';
import { createProgress } from '../../core/progress.js';
import { refreshSteering } from '../init.js';

const BUG_KEYWORDS = /\b(fix|bug|patch|typo|hotfix|broken|crash|error)\b/i;
const SMALL_KEYWORDS = /\b(rename|remove|delete|update|change|move|tweak)\b/i;

export async function createCmd({ description, name, size, promptOnly, cwd = process.cwd() }) {
  const specName = name || slugify(description);

  // Size hint
  if (size === 'large' && BUG_KEYWORDS.test(description)) {
    console.log(chalk.yellow(`\n  Hint: Looks like a small change — consider --size small`));
  } else if (size === 'large' && SMALL_KEYWORDS.test(description)) {
    console.log(chalk.yellow(`\n  Hint: Looks like a medium change — consider --size medium`));
  }

  const sizeLabel = { small: chalk.red('small'), medium: chalk.yellow('medium'), large: chalk.green('large') }[size];
  console.log(`\n${chalk.bold('sdd spec create')} — ${chalk.cyan(specName)} (${sizeLabel})\n`);

  const steering = readSteering(cwd);
  const modules = readModuleSpecs(cwd);
  const steeringBlock = Object.values(steering).join('\n\n---\n\n');
  const modulesBlock = Object.entries(modules).map(([name, content]) =>
    `### Module: ${name}\n${content}`
  ).join('\n\n');
  const projectContext = [steeringBlock, modulesBlock].filter(Boolean).join('\n\n---\n\n');

  const spinner = ora('Generating spec via Claude Code...').start();

  const onProgress = createProgress(spinner);

  try {
    const result = await generateCreateSpec({ description, specName, size, projectContext, promptOnly, cwd, onProgress });

    if (result.mode === Mode.CLAUDE) {
      spinner.succeed('Spec generated by Claude Code');
      // Claude Code wrote the files directly — verify they exist
      const specDir = path.join(cwd, 'specs', 'features', specName);
      if (fs.existsSync(specDir)) {
        const files = fs.readdirSync(specDir).filter(f => f.endsWith('.md'));
        for (const f of files) {
          console.log(`  ${chalk.green('created')} specs/features/${specName}/${f}`);
        }
      }
      // Auto-refresh steering docs
      await refreshSteering({ cwd, silent: false });
    } else {
      spinner.info('Claude Code not found — prompt saved');
      const specDir = path.join(cwd, 'specs', 'features', specName);
      fs.mkdirSync(specDir, { recursive: true });
      const promptPath = path.join(specDir, 'create_prompt.md');
      fs.writeFileSync(promptPath, result.prompt, 'utf-8');
      console.log(chalk.dim(`  ${path.relative(cwd, promptPath)}`));
      console.log(chalk.dim(`\n  Paste the prompt into Claude Code to generate the spec.`));
    }
    console.log('');
  } catch (err) {
    onProgress.stop();
    spinner.fail('Failed to generate spec');
    console.error(chalk.red(`\n  ${err.message}`));
    if (err.message.includes('ENOENT') || err.message.includes('not found')) {
      console.log(chalk.dim('  Install Claude Code: npm install -g @anthropic-ai/claude-code'));
    }
    console.log('');
  }
}

function slugify(s) {
  const slug = s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);
  return slug.startsWith('feat-') ? slug : `feat-${slug}`;
}
